# fly.toml app configuration file generated for spinout-mlks on 2026-04-01T15:58:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spinout-mlks'
primary_region = 'gru'

[build]

[mounts]
  source = "spinout_data"
  destination = "/app/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
